### ISSUE TITLE
RUN ERROR

### ISSUE THREAD

**Issue by superdabuniu** [2U1/Phi3-Vision-Finetune#35]
### Problem
module src/training/trainer.py  line 206
state_dict = {k:v for k, v in state_dict.items() if "wte" not in k}
Error: state_dict is None

### Background
I just run scripts/finetune.sh on single A100 GPU. Due to lack of  mpi4py, my environment can't use deepspeed, so I remove the --deepspeed scrpits/zero3.json.

### My solution
Before this line, I add the following line refer to line 190-191
if state_dict is None:
    state_dict = self.model.state_dict()

Is it correct?

**Comment by 2U1** [comment]
Yes I've fixed the trainer code. 
I didn't noticed it since I was only using deepspeed. Thanks.

https://github.com/2U1/Phi3-Vision-Finetune/blob/e4a5cd96bfe3e0e4baeb0aab3045dc95a9ddd22a/src/training/trainer.py#L206-L207

**Comment by 2U1** [comment]
That's becuase the auto config model name has changed you need to open the config file and fix it.
I've made a modifying code but I don't know why it's not working in your case right now. 

Change the autoconfig in config.json like 
"AutoConfig": "microsoft/Phi-3.5-vision-instruct--configuration_phi3_v.Phi3VConfig"

**Comment by superdabuniu** [comment]
> That's becuase the auto config model name has changed you need to open the config file and fix it. I've made a modifying code but I don't know why it's not working in your case right now.
> 
> Change the autoconfig in config.json like "AutoConfig": "microsoft/Phi-3.5-vision-instruct--configuration_phi3_v.Phi3VConfig"

my environment is offline, I download the phi-3.5-vision-instruct in my disk.

**Comment by 2U1** [comment]
@superdabuniu You could change the model loading script in utils.py
https://github.com/2U1/Phi3-Vision-Finetune/blob/e4a5cd96bfe3e0e4baeb0aab3045dc95a9ddd22a/src/utils.py#L44-L46
to load it from your local directory.

**Comment by superdabuniu** [comment]
> @superdabuniu You could change the model loading script in utils.py
> 
> https://github.com/2U1/Phi3-Vision-Finetune/blob/e4a5cd96bfe3e0e4baeb0aab3045dc95a9ddd22a/src/utils.py#L44-L46
> 
> 
> to load it from your local directory.

I have modified the model_base to my local path, but it still can't work.

Exact wrong at line 46 in /src/utils.py file. the error message is following:
```python
File "/.cache/huggingface/modules/transformers_modules/phi_3.5_vision_instruct/modeling_phi3_v.py", line 47, in <module>
    from .configuration_phi3_v import Phi3VConfig
ModuleNotFoundError: No module named 'transformers_modules.phi_3'
```
